image: node:17-alpine
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH!="main" &&  $CI_PIPELINE_SOURCE !="merge_request_event"
      when: never
    - when: always

stages:
  - test
  - build
  - deploy

run_unit_tests:
  stage: test
  before_script: # will run before the test data
    - eco $CI_PIPELINE_SOURCE
    - echo "Preparing the test data"
    - chmod +x prepare-tests.sh
    - ./prepare-tests.sh
  script:
    - echo "runing test...."
  after_script:
    - echo "cleaning the data test"

run_lint_tests:
  stage: test
  needs:
    - run_unit_tests
  script:
    - echo "building and tagging the docker image"

build_image:
  stage: build
  only:
    - main
  script:
    - echo "building the docker image"

push_image:
  stage: build
  only:
    - main
  needs: # it needs build_image jobs to run before push image runs
    - build_image
  script:
    - echo "pushing image"

deploy_image:
  stage: deploy
  only:
    - main
  script:
    - echo "Logging and pushing into doc ker registrly"
